In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [9]:
df_dados = pd.read_excel('dados3.xlsx')

In [15]:
df_dados.groupby(['IDADE']).count()

,TIPO DE MORTE,ANO,DATA,HORA,CIDADE,BAIRRO DA OCORRENCIA,LOGRADOURO DA OCORRENCIA,GENERO,ETNIA,PROFISSAO,ESCOLARIDADE,INSTRUMENTO UTILIZADO,ID
IDADE,,,,,,,,,,,,,
0,3,3,3,3,3,3,3,3,3,3,3,3,3
1,1,1,1,1,1,1,1,1,1,1,1,1,1
2,1,1,1,1,1,1,1,1,1,1,1,1,1
3,2,2,2,2,2,2,2,2,2,2,2,2,2
4,1,1,1,1,1,1,1,1,1,1,1,1,1
6,1,1,1,1,1,1,1,1,1,1,1,1,1
7,1,1,1,1,1,1,1,1,1,1,1,1,1
8,1,1,1,1,1,1,1,1,1,1,1,1,1
10,1,1,1,1,1,1,1,1,1,1,1,1,1
11,1,1,1,1,1,1,1,1,1,1,1,1,1
12,1,1,1,1,1,1,1,1,1,1,1,1,1
13,6,6,6,6,6,6,6,6,6,6,6,6,6
14,25,25,25,25,25,25,25,25,25,25,25,25,25
15,64,64,64,64,64,64,64,64,64,64,64,64,64
16,106,106,106,106,106,106,106,106,106,106,106,106,106
17,131,131,131,131,131,131,131,131,131,131,131,131,131
18,151,151,151,151,151,151,151,151,151,151,151,151,151
19,171,171,171,171,171,171,171,171,171,171,171,171,171
20,176,176,176,176,176,176,176,176,176,176,176,176,176
21,150,150,150,150,150,150,150,150,150,150,150,150,150
22,165,165,165,165,165,165,165,165,165,165,165,165,165
23,139,139,139,139,139,139,139,139,139,139,139,139,139
24,151,151,151,151,151,151,151,151,151,151,151,151,151
25,118,118,118,118,118,118,118,118,118,118,118,118,118
26,110,110,110,110,110,110,110,110,110,110,110,110,110
27,147,147,147,147,147,147,147,147,147,147,147,147,147
28,118,118,118,118,118,118,118,118,118,118,118,118,118
29,98,98,98,98,98,98,98,98,98,98,98,98,98
30,80,80,80,80,80,80,80,80,80,80,80,80,80
31,76,76,76,76,76,76,76,76,76,76,76,76,76
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48,24,24,24,24,24,24,24,24,24,24,24,24,24
49,21,21,21,21,21,21,21,21,21,21,21,21,21
50,19,19,19,19,19,19,19,19,19,19,19,19,19
51,16,16,16,16,16,16,16,16,16,16,16,16,16
52,13,13,13,13,13,13,13,13,13,13,13,13,13
53,11,11,11,11,11,11,11,11,11,11,11,11,11
54,11,11,11,11,11,11,11,11,11,11,11,11,11
55,10,10,10,10,10,10,10,10,10,10,10,10,10
56,5,5,5,5,5,5,5,5,5,5,5,5,5
57,6,6,6,6,6,6,6,6,6,6,6,6,6
58,8,8,8,8,8,8,8,8,8,8,8,8,8
59,9,9,9,9,9,9,9,9,9,9,9,9,9
60,6,6,6,6,6,6,6,6,6,6,6,5,6
61,5,5,5,5,5,5,5,5,5,5,5,5,5
62,5,5,5,5,5,5,5,5,5,5,5,5,5
63,1,1,1,1,1,1,1,1,1,1,1,1,1
65,4,4,4,4,4,4,4,4,4,4,4,4,4
66,1,1,1,1,1,1,1,1,1,1,1,1,1
67,3,3,3,3,3,3,3,3,3,3,3,3,3
68,1,1,1,1,1,1,1,1,1,1,1,1,1
70,4,4,4,4,4,4,4,4,4,4,4,4,4
71,1,1,1,1,1,1,1,1,1,1,1,1,1
73,1,1,1,1,1,1,1,1,1,1,1,1,1
74,2,2,2,2,2,2,2,2,2,2,2,2,2
75,1,1,1,1,1,1,1,1,1,1,1,1,1
78,2,2,2,2,2,2,2,2,2,2,2,2,2
80,2,2,2,2,2,2,2,2,2,2,2,2,2
84,1,1,1,1,1,1,1,1,1,1,1,1,1
86,2,2,2,2,2,2,2,2,2,2,2,2,2
89,1,1,1,1,1,1,1,1,1,1,1,1,1

In [4]:
df_dados[(df_dados['BAIRRO DA OCORRENCIA'] == 'FELIPE CAMARÃO') & (df_dados['ANO'] == 2013)].groupby(['ANO', 'HORA']).count()

               TIPO DE MORTE  DATA  CIDADE  BAIRRO DA OCORRENCIA  \
ANO  HORA
2013 00:11:00              4     4       4                     4
     02:01:00              1     1       1                     1
     03:27:00              2     2       2                     2
     05:30:00              1     1       1                     1
     06:30:00              1     1       1                     1
     11:44:00              2     2       2                     2
     12:29:00              1     1       1                     1
     13:38:00              3     3       3                     3
     14:25:00              1     1       1                     1
     14:51:00              9     9       9                     9
     15:15:00              1     1       1                     1
     17:01:00              1     1       1                     1
     17:04:00              2     2       2                     2
     18:13:00              1     1       1                     1
     18:41:00              1     1       1                     1
     19:25:00              1     1       1                     1
     19:54:00              1     1       1                     1
     20:08:00              1     1       1                     1
     20:14:00              4     4       4                     4
     20:36:00              1     1       1                     1
     20:43:00              1     1       1                     1
     21:22:00              2     2       2                     2
     21:35:00              1     1       1                     1
     21:39:00              5     5       5                     5
     22:00:00              1     1       1                     1
     22:20:00              1     1       1                     1
     22:55:00              1     1       1                     1
     NI                    4     4       4                     4

               LOGRADOURO DA OCORRENCIA  GENERO  ETNIA  IDADE  PROFISSAO  \
ANO  HORA
2013 00:11:00                         4       4      4      4          4
     02:01:00                         1       1      1      1          1
     03:27:00                         2       2      2      2          2
     05:30:00                         1       1      1      1          1
     06:30:00                         1       1      1      1          1
     11:44:00                         2       2      2      2          2
     12:29:00                         1       1      1      1          1
     13:38:00                         3       3      3      3          3
     14:25:00                         1       1      1      1          1
     14:51:00                         9       9      9      9          9
     15:15:00                         1       1      1      1          1
     17:01:00                         1       1      1      1          1
     17:04:00                         2       2      2      2          2
     18:13:00                         1       1      1      1          1
     18:41:00                         1       1      1      1          1
     19:25:00                         1       1      1      1          1
     19:54:00                         1       1      1      1          1
     20:08:00                         1       1      1      1          1
     20:14:00                         4       4      4      4          4
     20:36:00                         1       1      1      1          1
     20:43:00                         1       1      1      1          1
     21:22:00                         2       2      2      2          2
     21:35:00                         1       1      1      1          1
     21:39:00                         5       5      5      5          5
     22:00:00                         1       1      1      1          1
     22:20:00                         1       1      1      1          1
     22:55:00                         1       1      1      1          1
     NI                               4       4      4      4          4

               ESCOLARIDADE  INSTRUMENTO UTILIZADO  ID
ANO  HORA
2013 00:11:00             4                      4   4
     02:01:00             1                      1   1
     03:27:00             2                      2   2
     05:30:00             1                      1   1
     06:30:00             1                      1   1
     11:44:00             2                      2   2
     12:29:00             1                      1   1
     13:38:00             3                      3   3
     14:25:00             1                      1   1
     14:51:00             9                      9   9
     15:15:00             1                      1   1
     17:01:00             1                      1   1
     17:04:00             2                      2   2
     18:13:00             1                      1   1
     18:41:00             1                      1   1
     19:25:00             1                      1   1
     19:54:00             1                      1   1
     20:08:00             1                      1   1
     20:14:00             4                      4   4
     20:36:00             1                      1   1
     20:43:00             1                      1   1
     21:22:00             2                      2   2
     21:35:00             1                      1   1
     21:39:00             5                      5   5
     22:00:00             1                      1   1
     22:20:00             1                      1   1
     22:55:00             1                      1   1
     NI                   4                      4   4

In [5]:
df_teste = df_dados[(df_dados['HORA'] != 'NI')]

In [6]:
type(df_teste['HORA'])

pandas.core.series.Series

In [7]:
df_dados[(df_dados['PROFISSAO'] == 'DESEMPREGADO') | (df_dados['PROFISSAO'] == 'DESEMPREGADO(A)') | (df_dados['PROFISSAO'] == 'DESEMPREGADA')].groupby(['IDADE', 'ANO']).count()

            TIPO DE MORTE  DATA  HORA  CIDADE  BAIRRO DA OCORRENCIA  \
IDADE ANO
14    2012              1     1     1       1                     1
15    2016              1     1     1       1                     1
      2017              5     5     5       5                     5
16    2012              1     1     1       1                     1
      2016              2     2     2       2                     2
      2017              6     6     6       6                     6
17    2012              4     4     4       4                     4
      2016              1     1     1       1                     1
      2017              7     7     7       7                     7
18    2012              3     3     3       3                     3
      2013              7     7     7       7                     7
      2014              3     3     3       3                     3
      2015              2     2     2       2                     2
      2016              3     3     3       3                     3
      2017             11    11    11      11                    11
19    2012              1     1     1       1                     1
      2013              4     4     4       4                     4
      2014              1     1     1       1                     1
      2015              7     7     7       7                     7
      2016             10    10    10      10                    10
      2017             13    13    13      13                    13
20    2012              4     4     4       4                     4
      2013              2     2     2       2                     2
      2014              5     5     5       5                     5
      2015              5     5     5       5                     5
      2016              3     3     3       3                     3
      2017             14    14    14      14                    14
21    2012              2     2     2       2                     2
      2013              3     3     3       3                     3
      2014              6     6     6       6                     6
...                   ...   ...   ...     ...                   ...
37    2014              1     1     1       1                     1
      2016              3     3     3       3                     3
      2017              1     1     1       1                     1
38    2012              2     2     2       2                     2
      2016              1     1     1       1                     1
      2017              2     2     2       2                     2
39    2013              1     1     1       1                     1
      2015              1     1     1       1                     1
      2017              3     3     3       3                     3
40    2013              1     1     1       1                     1
      2017              2     2     2       2                     2
41    2012              1     1     1       1                     1
      2015              1     1     1       1                     1
      2016              1     1     1       1                     1
      2017              1     1     1       1                     1
42    2014              1     1     1       1                     1
      2015              1     1     1       1                     1
43    2016              1     1     1       1                     1
      2017              4     4     4       4                     4
45    2015              2     2     2       2                     2
      2016              1     1     1       1                     1
46    2017              2     2     2       2                     2
47    2012              1     1     1       1                     1
48    2016              1     1     1       1                     1
49    2017              1     1     1       1                     1
51    2016              1     1     1       1                     1
55    2017              1     1     1       1                     1
57    2017              1     1     1       1                     1
60    2017              1     1     1       1                     1
68    2017              1     1     1       1                     1

            LOGRADOURO DA OCORRENCIA  GENERO  ETNIA  PROFISSAO  ESCOLARIDADE  \
IDADE ANO
14    2012                         1       1      1          1             1
15    2016                         1       1      1          1             1
      2017                         5       5      5          5             5
16    2012                         1       1      1          1             1
      2016                         2       2      2          2             2
      2017                         6       6      6          6             6
17    2012                         4       4      4          4             4
      2016                         1       1      1          1             1
      2017                         7       7      7          7             7
18    2012                         3       3      3          3             3
      2013                         7       7      7          7             7
      2014                         3       3      3          3             3
      2015                         2       2      2          2             2
      2016                         3       3      3          3             3
      2017                        11      11     11         11            11
19    2012                         1       1      1          1             1
      2013                         4       4      4          4             4
      2014                         1       1      1          1             1
      2015                         7       7      7          7             7
      2016                        10      10     10         10            10
      2017                        13      13     13         13            13
20    2012                         4       4      4          4             4
      2013                         2       2      2          2             2
      2014                         5       5      5          5             5
      2015                         5       5      5          5             5
      2016                         3       3      3          3             3
      2017                        14      14     14         14            14
21    2012                         2       2      2          2             2
      2013                         3       3      3          3             3
      2014                         6       6      6          6             6
...                              ...     ...    ...        ...           ...
37    2014                         1       1      1          1             1
      2016                         3       3      3          3             3
      2017                         1       1      1          1             1
38    2012                         2       2      2          2             2
      2016                         1       1      1          1             1
      2017                         2       2      2          2             2
39    2013                         1       1      1          1             1
      2015                         1       1      1          1             1
      2017                         3       3      3          3             3
40    2013                         1       1      1          1             1
      2017                         2       2      2          2             2
41    2012                         1       1      1          1             1
      2015                         1       1      1          1             1
      2016                         1       1      1          1             1
      2017                         1       1      1          1             1
42    2014                         1       1      1          1             1
      2015                         1       1      1          1             1
43    2016                         1       1      1          1             1
      2017                         4       4      4          4             4
45    2015                         2       2      2          2             2
      2016                         1       1      1          1             1
46    2017                         2       2      2          2             2
47    2012                         1       1      1          1             1
48    2016                         1       1      1          1             1
49    2017                         1       1      1          1             1
51    2016                         1       1      1          1             1
55    2017                         1       1      1          1             1
57    2017                         1       1      1          1             1
60    2017                         1       1      1          1             1
68    2017                         1       1      1          1             1

            INSTRUMENTO UTILIZADO  ID
IDADE ANO
14    2012                      1   1
15    2016                      1   1
      2017                      5   5
16    2012                      1   1
      2016                      2   2
      2017                      6   6
17    2012                      4   4
      2016                      1   1
      2017                      7   7
18    2012                      3   3
      2013                      7   7
      2014                      3   3
      2015                      2   2
      2016                      3   3
      2017                     11  11
19    2012                      1   1
      2013                      4   4
      2014                      1   1
      2015                      7   7
      2016                     10  10
      2017                     13  13
20    2012                      4   4
      2013                      2   2
      2014                      5   5
      2015                      5   5
      2016                      3   3
      2017                     14  14
21    2012                      2   2
      2013                      3   3
      2014                      6   6
...                           ...  ..
37    2014                      1   1
      2016                      3   3
      2017                      1   1
38    2012                      2   2
      2016                      1   1
      2017                      2   2
39    2013                      1   1
      2015                      1   1
      2017                      3   3
40    2013                      1   1
      2017                      2   2
41    2012                      1   1
      2015                      1   1
      2016                      1   1
      2017                      1   1
42    2014                      1   1
      2015                      1   1
43    2016                      1   1
      2017                      4   4
45    2015                      2   2
      2016                      1   1
46    2017                      2   2
47    2012                      1   1
48    2016                      1   1
49    2017                      1   1
51    2016                      1   1
55    2017                      1   1
57    2017                      1   1
60    2017                      0   1
68    2017                      1   1

[136 rows x 12 columns]

In [8]:
df_dados[(df_dados['ANO'] == 2013)].groupby(['ANO', 'HORA']).count()

               TIPO DE MORTE  DATA  CIDADE  BAIRRO DA OCORRENCIA  \
ANO  HORA
2013 00:11:00             24    24      24                    24
     00:34:00              3     3       3                     3
     00:43:00              1     1       1                     1
     00:45:00              1     1       1                     1
     00:50:00              2     2       2                     2
     00:51:00              8     8       8                     8
     01:00:00              1     1       1                     1
     01:27:00              4     4       4                     4
     01:45:00              3     3       3                     3
     02:01:00              1     1       1                     1
     02:30:00              7     7       7                     7
     03:27:00             18    18      18                    18
     05:30:00              4     4       4                     4
     06:30:00              2     2       2                     2
     08:37:00              5     5       5                     5
     09:39:00              1     1       1                     1
     10:07:00              6     6       6                     6
     10:20:00              1     1       1                     1
     11:44:00             28    28      28                    28
     12:29:00              5     5       5                     5
     13:05:00             10    10      10                    10
     13:07:00              1     1       1                     1
     13:21:00              1     1       1                     1
     13:38:00             28    28      28                    28
     13:58:00              1     1       1                     1
     13:59:00             14    14      14                    14
     14:25:00              6     6       6                     6
     14:32:00              1     1       1                     1
     14:51:00             62    62      62                    62
     15:05:00              2     2       2                     2
...                      ...   ...     ...                   ...
     19:25:00              1     1       1                     1
     19:29:00              1     1       1                     1
     19:54:00             14    14      14                    14
     20:02:00              2     2       2                     2
     20:08:00              3     3       3                     3
     20:14:00             26    26      26                    26
     20:15:00              1     1       1                     1
     20:17:00              5     5       5                     5
     20:33:00              3     3       3                     3
     20:36:00              4     4       4                     4
     20:39:00              3     3       3                     3
     20:42:00              3     3       3                     3
     20:43:00              7     7       7                     7
     20:48:00              2     2       2                     2
     21:11:00              2     2       2                     2
     21:22:00              3     3       3                     3
     21:31:00              2     2       2                     2
     21:35:00              8     8       8                     8
     21:38:00              9     9       9                     9
     21:39:00             59    59      59                    59
     21:49:00              1     1       1                     1
     22:00:00              3     3       3                     3
     22:20:00              2     2       2                     2
     22:35:00              1     1       1                     1
     22:39:00              2     2       2                     2
     22:55:00             12    12      12                    12
     23:06:00              1     1       1                     1
     23:09:00              4     4       4                     4
     23:42:00              2     2       2                     2
     NI                   50    50      50                    50

               LOGRADOURO DA OCORRENCIA  GENERO  ETNIA  IDADE  PROFISSAO  \
ANO  HORA
2013 00:11:00                        24      24     24     24         24
     00:34:00                         3       3      3      3          3
     00:43:00                         1       1      1      1          1
     00:45:00                         1       1      1      1          1
     00:50:00                         2       2      2      2          2
     00:51:00                         8       8      8      8          8
     01:00:00                         1       1      1      1          1
     01:27:00                         4       4      4      4          4
     01:45:00                         3       3      3      3          3
     02:01:00                         1       1      1      1          1
     02:30:00                         7       7      7      7          7
     03:27:00                        18      18     18     18         18
     05:30:00                         4       4      4      4          4
     06:30:00                         2       2      2      2          2
     08:37:00                         5       5      5      5          5
     09:39:00                         1       1      1      1          1
     10:07:00                         6       6      6      6          6
     10:20:00                         1       1      1      1          1
     11:44:00                        28      28     28     28         28
     12:29:00                         5       5      5      5          5
     13:05:00                        10      10     10     10         10
     13:07:00                         1       1      1      1          1
     13:21:00                         1       1      1      1          1
     13:38:00                        28      28     28     28         28
     13:58:00                         1       1      1      1          1
     13:59:00                        14      14     14     14         14
     14:25:00                         6       6      6      6          6
     14:32:00                         1       1      1      1          1
     14:51:00                        62      62     62     62         62
     15:05:00                         2       2      2      2          2
...                                 ...     ...    ...    ...        ...
     19:25:00                         1       1      1      1          1
     19:29:00                         1       1      1      1          1
     19:54:00                        14      14     14     14         14
     20:02:00                         2       2      2      2          2
     20:08:00                         3       3      3      3          3
     20:14:00                        26      26     26     26         26
     20:15:00                         1       1      1      1          1
     20:17:00                         5       5      5      5          5
     20:33:00                         3       3      3      3          3
     20:36:00                         4       4      4      4          4
     20:39:00                         3       3      3      3          3
     20:42:00                         3       3      3      3          3
     20:43:00                         7       7      7      7          7
     20:48:00                         2       2      2      2          2
     21:11:00                         2       2      2      2          2
     21:22:00                         3       3      3      3          3
     21:31:00                         2       2      2      2          2
     21:35:00                         8       8      8      8          8
     21:38:00                         9       9      9      9          9
     21:39:00                        59      59     59     59         59
     21:49:00                         1       1      1      1          1
     22:00:00                         3       3      3      3          3
     22:20:00                         2       2      2      2          2
     22:35:00                         1       1      1      1          1
     22:39:00                         2       2      2      2          2
     22:55:00                        12      12     12     12         12
     23:06:00                         1       1      1      1          1
     23:09:00                         4       4      4      4          4
     23:42:00                         2       2      2      2          2
     NI                              50      50     50     50         50

               ESCOLARIDADE  INSTRUMENTO UTILIZADO  ID
ANO  HORA
2013 00:11:00            24                     24  24
     00:34:00             3                      3   3
     00:43:00             1                      1   1
     00:45:00             1                      1   1
     00:50:00             2                      2   2
     00:51:00             8                      8   8
     01:00:00             1                      1   1
     01:27:00             4                      4   4
     01:45:00             3                      3   3
     02:01:00             1                      1   1
     02:30:00             7                      7   7
     03:27:00            18                     18  18
     05:30:00             4                      4   4
     06:30:00             2                      2   2
     08:37:00             5                      5   5
     09:39:00             1                      1   1
     10:07:00             6                      6   6
     10:20:00             1                      1   1
     11:44:00            28                     28  28
     12:29:00             5                      5   5
     13:05:00            10                     10  10
     13:07:00             1                      1   1
     13:21:00             1                      1   1
     13:38:00            28                     28  28
     13:58:00             1                      1   1
     13:59:00            14                     14  14
     14:25:00             6                      6   6
     14:32:00             1                      1   1
     14:51:00            62                     62  62
     15:05:00             2                      2   2
...                     ...                    ...  ..
     19:25:00             1                      1   1
     19:29:00             1                      1   1
     19:54:00            14                     14  14
     20:02:00             2                      2   2
     20:08:00             3                      3   3
     20:14:00            26                     26  26
     20:15:00             1                      1   1
     20:17:00             5                      5   5
     20:33:00             3                      3   3
     20:36:00             4                      4   4
     20:39:00             3                      3   3
     20:42:00             3                      3   3
     20:43:00             7                      7   7
     20:48:00             2                      2   2
     21:11:00             2                      2   2
     21:22:00             3                      3   3
     21:31:00             2                      2   2
     21:35:00             8                      8   8
     21:38:00             9                      9   9
     21:39:00            59                     59  59
     21:49:00             1                      1   1
     22:00:00             3                      3   3
     22:20:00             2                      2   2
     22:35:00             1                      1   1
     22:39:00             2                      2   2
     22:55:00            12                     12  12
     23:06:00             1                      1   1
     23:09:00             4                      4   4
     23:42:00             2                      2   2
     NI                  50                     50  50

[73 rows x 12 columns]